PULP_APP = test
PULP_APP_FC_SRCS = test.c
PULP_APP_HOST_SRCS = test.c
PULP_CFLAGS = -O3 -g

RISCV_RCP_SDK_PATH = /work/pulpissimo/fpga/sw/sdk

# Configuration
##include /work/pulpissimo/fpga/sw/sdk/pulp_app.mk
include $(RISCV_RCP_SDK_PATH)/pulp_app.mk
